jobs:
  - name: verify-v-6-6-4
    type: runSh
    steps:
      - IN: master-gitRepo
      - IN: sample_kv_int
      - IN: sample_aws
      - TASK:
          name: check-get-git-changes
          script:
            - echo "hello"
            - shipctl get_git_changes --resource="master-gitRepo"
      - TASK:
          name: get_integration_resource_field
          script:
            - shipctl get_integration_resource_field sample_kv_int key1
            - shipctl get_integration_resource_field sample_aws accessKey
            
resources:          
  - name: master-gitRepo
    type: gitRepo
    integration: drship_github
    pointer:
      sourceName: sample-organisation/gitRepo
      branch: prod_get_git_changes
      buildOnPullRequest: true

  - name: sample_kv_int
    type: integration
    integration: sample_kv
    
