jobs:
  - name: verify-v-6-6-4
    type: runSh
    steps:
      - IN: master-gitRepo
      - IN: sample_kv_int
      - TASK:
          name: check-get-git-changes
          script:
            - echo "hello"
            - shipctl get_git_changes --resource="master-gitRepo"
      - TASK:
          name: get_integration_resource_field
          script:
            - shipctl get_integration_resource_field sample_kv_int key1
            
  - name: verify-v-6-7-4
    type: runSh
    steps:
      - IN: sample_kv_int
      - IN: sample_aws_int
      # remove clone step after release
      - TASK:
          name: patched
          script:
            - git clone https://github.com/scriptnull/node.git nodeRepo
            - ./nodeRepo/shipctl/x86_64/Ubuntu_16.04/install.sh
            - shipctl get_integration_resource_field sample_kv_int key1
            - shipctl get_integration_resource_field sample_kv_int invalid_key
            - shipctl get_integration_resource_field sample_aws_int accessKey
            - shipctl get_integration_resource_field sample_aws_int invalid_key
            - shipctl get_integration_resource_field invalid_resource_name accessKey
      - TASK:
          name: unpatched
          script:
            - shipctl get_integration_resource_field sample_kv_int key1
            - shipctl get_integration_resource_field sample_kv_int invalid_key
            - shipctl get_integration_resource_field sample_aws_int accessKey
            - shipctl get_integration_resource_field sample_aws_int invalid_key
            - shipctl get_integration_resource_field invalid_resource_name accessKey

resources:          
  - name: master-gitRepo
    type: gitRepo
    integration: drship_github
    pointer:
      sourceName: sample-organisation/gitRepo
      branch: prod_get_git_changes
      buildOnPullRequest: true

  - name: sample_kv_int
    type: integration
    integration: sample_kv
    
  - name: sample_aws_int
    type: integration
    integration: sample_aws
    
